name: real_robots
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - intel-openmp=2020.2
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.6.9
  - readline=7.0
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.11.0
    - aicrowd-api==0.1.23
    - astunparse==1.6.3
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.6.0
    - crlibm==1.0.3
    - cycler==0.10.0
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.33.2
    - gym==0.17.3
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==2.0.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.3.3
    - oauthlib==3.1.0
    - opencv-python==4.4.0.46
    - opt-einsum==3.3.0
    - pillow==8.0.1
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==3.0.6
    - pyglet==1.5.0
    - pyinterval==1.2.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pyyaml==5.3.1
    - real-robots==0.1.21
    - redis==3.5.3
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.4
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - tqdm==4.51.0
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.4.0
prefix: /root/anaconda3/envs/real_robots

